name:                apollo
version:             0.1.0.0
github:              "github.com/Arthur-Aillet/Apollo"
license:             GPL-3
author:
  - "Auguste Frater"
  - "Julian Scott"
  - "Ludovic De-Chavagnac"
  - "Arthur Aillet"
maintainer:
  - "aguste.frater@epitech.eu"
  - "julian.scott@epitech.eu"
  - "ludovic.de-chavagnac@epitech.eu"
  - "arthur.aillet@epitech.eu"
copyright:           "2023 Arthur Aillet"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Arthur-Aillet/Apollo#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers
- process
- bytestring
- binary

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-incomplete-uni-patterns
- -Wno-incomplete-patterns

library:
  source-dirs:
  - src
executables:
  apollo:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - apollo
    - haskeline

tests:
  apollo-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - apollo
    - haskeline
    - HUnit
